#!/bin/bash
# Initial environment variables using my preferences. To use this:
#
#   source ./initial-env
#
# See the install script for what these mean and possible values

XDG_DATA_HOME="${XDG_DATA_HOME:-$HOME/.local/share}"

# Uncomment this to turn on debug logging
#export PYENV_DEBUG=yes
# Uncomment this if you don't want this script to handle instaling dependencies
#export PYENV_SKIP_UPDATE=yes
export PYENV_ROOT="$XDG_DATA_HOME/pyenv"
export PYENV_INITIAL_VERSION='system'
