#!/bin/bash
# Initial environment variables using my preferences. To use this:
#
#   source ./initial-env
#
# See the install script for what these mean and possible values

XDG_DATA_HOME="${XDG_DATA_HOME:-$HOME/.local/share}"

export PYENV_ROOT="$XDG_DATA_HOME/pyenv"
export PYENV_INITIAL_VERSION='system'
